<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="7" time="30.176" timestamp="2022-07-25T19:54:34.072498" hostname="DESKTOP-CTCCQ2D"><testcase classname="tests.Test_registration.Test_regisration" name="test_click_create_account_button" time="0.851" /><testcase classname="tests.Test_registration.Test_regisration" name="test_click_for_myself_button" time="2.735" /><testcase classname="tests.Test_registration.Test_regisration" name="test_input_first_name" time="5.965" /><testcase classname="tests.Test_registration.Test_regisration" name="test_input_last_name" time="2.174" /><testcase classname="tests.Test_registration.Test_regisration" name="test_input_password" time="4.908" /><testcase classname="tests.Test_registration.Test_regisration" name="test_confirm_input_password" time="2.820" /><testcase classname="tests.Test_registration.Test_regisration" name="test_click_checkbox" time="10.646"><failure message="Exception: Element by &quot;xpath&quot; with the value &quot;/html/body/div[1]/div[1]/div[2]/div[1]/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[3]/div[3]/div/div[1]/div/div/div[1]/div/input&quot; cannot be found.">E   selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:
E   Exception: Element by "xpath" with the value "/html/body/div[1]/div[1]/div[2]/div[1]/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div[3]/div[3]/div/div[1]/div/div/div[1]/div/input" cannot be found.</failure></testcase></testsuite></testsuites>